/*
00_create_tables.sql

PURPOSE:
    - Create the Ravenstack schema and base tables used in this project.
    - Reset the database to a clean state so the project is reproducible.
    - Define datatypes, primary keys, and foreign keys.
*/

CREATE SCHEMA IF NOT EXISTS ravenstack;
SET search_path = ravenstack;

/*
NOTE: Drop order matters because of foreign keys.
Drop child tables first, then parent tables.
Safe drop order for this schema:
    1. feature_usage_raw ->
    2. support_tickets ->
    3. churn_events ->
    4. subscriptions ->
    5. accounts
*/
DROP TABLE IF EXISTS feature_usage_raw;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS churn_events;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS accounts;

-- accounts: one row per customer account.
-- This is the parent table referenced by subscriptions, churn_events, and support_tickets.
CREATE TABLE accounts (
    account_id text PRIMARY KEY,
    account_name text,
    industry text,
    country text,
    signup_date date,
    referral_source text,
    plan_tier text,
    seats int,
    is_trial boolean,
    churn_flag boolean
);

-- subscriptions: subscription history by account.
-- Used to compute paying status and month-end MRR summaries.
-- start_date and end_date define the active window for a subscription.
-- end-date values can be NULL, indicating the subscription is still active.
CREATE TABLE subscriptions (
    subscription_id text PRIMARY KEY,
    account_id text REFERENCES accounts(account_id),
    start_date date NOT NULL,
    end_date date,
    plan_tier text,
    seats int,
    mrr_amount numeric(12,2),
    arr_amount numeric(12,2),
    is_trial boolean,
    upgrade_flag boolean,
    downgrade_flag boolean,
    churn_flag boolean,
    billing_frequency text,
    auto_renew_flag boolean
);

-- feature_usage_raw: landing/raw table showing product usage events loaded as-is from the CSV.
-- usage_id may be duplicated in the source file, so PK is not enforced as it fails to load.
-- row_id is a surrogate key generated by Postgres for row identity.
CREATE TABLE feature_usage_raw (
    row_id bigserial PRIMARY KEY,
    usage_id text,
    subscription_id text REFERENCES subscriptions(subscription_id),
    usage_date date NOT NULL,
    feature_name text,
    usage_count int,
    usage_duration_secs int,
    error_count int,
    is_beta_feature boolean
);

-- support_tickets: support operations data for hypothesis building.
-- This is optional for churn math, but useful for explaining churn drivers.
CREATE TABLE support_tickets (
    ticket_id text PRIMARY KEY,
    account_id text REFERENCES accounts(account_id),
    submitted_at timestamp,
    closed_at timestamp,
    resolution_time_hours numeric(12,2),
    priority text,
    first_response_time_minutes int,
    satisfaction_score numeric(6,2),
    escalation_flag boolean
);

-- churn_events: event log for churn reasons and context.
-- Can serve as qualitative support for why churn happened.
CREATE TABLE churn_events (
    churn_event_id text PRIMARY KEY,
    account_id text REFERENCES accounts(account_id),
    churn_date date NOT NULL,
    reason_code text,
    refund_amount_usd numeric(12,2),
    preceding_upgrade_flag boolean,
    preceding_downgrade_flag boolean,
    is_reactivation boolean,
    feedback_text text
);

-- idx_subsciptions_account_id
-- Speeds up joins from accounts -> subscriptions (account_id is the bridge).
CREATE INDEX IF NOT EXISTS idx_subscriptions_account_id
    ON subscriptions(account_id);

-- idx_usage_raw_sub_date
-- Speeds up joins from feature_usage_raw -> subscriptions using subscription_id
CREATE INDEX IF NOT EXISTS idx_usage_raw_sub_date
    ON feature_usage_raw(subscription_id, usage_date);

-- idx_churn_events_account_date
-- Speeds up queries that look up churn history for an account over time.
CREATE INDEX IF NOT EXISTS idx_churn_events_account_date
    ON churn_events(account_id, churn_date);